name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  # push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      #Moving the workflow on the VM
      - name: Checkout Code
        uses: actions/checkout@v4

      #Node.js installation for vite
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      #Dependecies intalation
      - name: Install Dependencies
        run: npm ci

      #Building
      - name: Build Project
        run: npm run build

      #Railway CLI on VM for deployment
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      #Deployment
      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}