name: CI Pipeline

on:
  push:
    branches:
      - main
      - test 
  pull_request:
    branches:
      - main
      - test 
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Build
    runs-on: ubuntu-latest

    #Workflow timeout after 5 minutes
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # - name: Tests
      #   run: npm run test

      - name: Build
        run: npm run build
